name: Exam CI

on:
  push:
    branches: [ "main" ]

jobs:
  check-exam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check file exists
        run: test -f index.html

      - name: Check file not empty
        run: test -s index.html

      - name: Check content
        run: |
          grep -q "Submit Answer" index.html || exit 1
          grep -q "questions" index.html || exit 1
