name: CICD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run CI check
        run: node index.js

      - name: Create output folder and file
        run: |
          mkdir -p deploy
          echo "CI/CD run successful " > deploy/result.txt
          cat deploy/result.txt


    